name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12 horas certinho
  workflow_dispatch:          # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Gerar animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: gcampolina
          outputs: dist/github-contribution-grid-snake.svg

      - name: Deploy no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
